#!/usr/bin/env python3
total = 0.0
for i in range(10):
    total += 0.1
print(f"Expected Result: 1.0\nActual Result: {total}")

from fractions import Fraction

result = Fraction('1.2') - Fraction('1.0')
print(f"Exact Fractional Result: {result}")