#!/usr/bin/env python3

number = 90
result = float(number)
print(result)

import sys

d1 = {'a': 1, 'b': 2, 'c': 3}

# Getting the size of the dictionary in bytes
size = sys.getsizeof(d1)

print(size)

d1 = {'a': 1, 'b': 2, 'c': 3}

# Getting the size of the dictionary using __sizeof__()
size = d1.__sizeof__()

print(size)

d = {'a': [1, 2, 3], 'b': [3, 4, 5], 'c': [5, 6]}
s = set()

# Remove duplicates across dictionary values
for key in d:
    d[key] = [v for v in d[key] if v not in s and not s.add(v)]

print(d)
